/**
 * Chrome copy of the city landing page (buttons, section titles, neutral fallbacks).
 * Keyed by the landing's own locale (SSR), not by the app's language toggle.
 * City-specific words never live here: they come from the config.
 */
export type LandingLocale = "es" | "en";

export const landingCopy = {
  es: {
    skip: "Ir al contenido",
    openApp: "Abrir la app",
    openAppShort: "Abrir",
    howItWorks: "Cómo funciona",
    heroTitle: (city: string) => `Muévete por ${city} con datos en vivo`,
    heroSubtitle: "Planea tu viaje, ubica tu bus y llega a tiempo. Gratis, sin cuenta y de código abierto.",
    downloads: "Descarga la app",
    ios: "Descargar en App Store",
    android: "Disponible en Google Play",
    web: "Usar en el navegador",
    stats: { routes: "rutas", stops: "paradas y estaciones", vehiclesLive: "buses en vivo ahora", bikeStations: "estaciones de bici", alertsActive: "alertas activas" },
    statsLive: "Cifras en vivo",
    statsUpdated: "actualizado",
    features: "Qué puedes hacer",
    genericHighlights: [
      { icon: "route", title: "Planea viajes multimodales", text: "Bus, cable, bici y a pie en un solo itinerario, con horarios y transbordos." },
      { icon: "live", title: "Buses en vivo", text: "La flota en el mapa, con posición real y llegadas estimadas." },
      { icon: "board", title: "Ubica tu bus", text: "Elige tu parada y tu ruta: te decimos cuándo llega el próximo." },
      { icon: "favorites", title: "Tus lugares y rutas", text: "Casa, trabajo y las rutas que usas, a un toque." },
      { icon: "open", title: "Datos abiertos", text: "Los mismos datos públicos que usa la ciudad, sin cuentas ni rastreadores." },
    ],
    screenshots: "Así se ve",
    partners: "Con datos de",
    openData: "Datos abiertos",
    openDataHint: "La app se alimenta de feeds públicos que cualquiera puede usar.",
    faq: "Preguntas frecuentes",
    contact: "Contacto",
    write: "Escríbenos",
    privacy: "Privacidad",
    terms: "Términos",
    madeWith: "Hecho con opentransit, software libre",
    poweredBy: "Mapa: © OpenMapTiles © OpenStreetMap contributors",
    disabledTitle: "Esta página no está publicada",
    disabledHint: "La ciudad aún no activó su página pública. La app sí está disponible.",
    previewBanner: "Vista previa del borrador sin guardar",
    closePreview: "Cerrar",
    bikeShare: "Bicis públicas de",
  },
  en: {
    skip: "Skip to content",
    openApp: "Open the app",
    openAppShort: "Open",
    howItWorks: "How it works",
    heroTitle: (city: string) => `Get around ${city} with live data`,
    heroSubtitle: "Plan your trip, find your bus and arrive on time. Free, no account, open source.",
    downloads: "Get the app",
    ios: "Download on the App Store",
    android: "Get it on Google Play",
    web: "Use it in the browser",
    stats: { routes: "routes", stops: "stops and stations", vehiclesLive: "buses live right now", bikeStations: "bike stations", alertsActive: "active alerts" },
    statsLive: "Live figures",
    statsUpdated: "updated",
    features: "What you can do",
    genericHighlights: [
      { icon: "route", title: "Plan multimodal trips", text: "Bus, cable car, bike and walking in one itinerary, with times and transfers." },
      { icon: "live", title: "Buses live", text: "The fleet on the map, real positions and estimated arrivals." },
      { icon: "board", title: "Find your bus", text: "Pick your stop and route: we tell you when the next one arrives." },
      { icon: "favorites", title: "Your places and routes", text: "Home, work and the routes you use, one tap away." },
      { icon: "open", title: "Open data", text: "The same public data the city uses, with no accounts or trackers." },
    ],
    screenshots: "What it looks like",
    partners: "With data from",
    openData: "Open data",
    openDataHint: "The app runs on public feeds anyone can use.",
    faq: "Frequently asked questions",
    contact: "Contact",
    write: "Write to us",
    privacy: "Privacy",
    terms: "Terms",
    madeWith: "Made with opentransit, free software",
    poweredBy: "Map: © OpenMapTiles © OpenStreetMap contributors",
    disabledTitle: "This page is not published",
    disabledHint: "The city has not enabled its public page yet. The app itself is available.",
    previewBanner: "Preview of the unsaved draft",
    closePreview: "Close",
    bikeShare: "Public bikes by",
  },
} as const;

export type LandingCopy = (typeof landingCopy)["es"];
export const copyFor = (locale: string | null | undefined): LandingCopy => (locale === "en" ? (landingCopy.en as unknown as LandingCopy) : landingCopy.es);
